export const theme = {
  colors: {
    primary: '#5FA8FF',
    secondary: '#F7F4E8',
    accent: '#D9A84E',
    backgroundTop: '#F5F9FF',
    backgroundBottom: '#EEF3FA',
    surface: '#FFFFFF',
    surfaceSoft: '#FBFDFF',
    textPrimary: '#2D3642',
    textSecondary: '#6A7688',
    border: '#DCE6F3',
    inputBackground: '#FFFFFF',
    inputBorder: '#C9D8EC',
    dropdownBackground: '#F7FAFF',
    dropdownBorder: '#C7D9F1',
    success: '#3E9B76',
    error: '#DC2626',
    info: '#4E88C7',
    warning: '#C18A2F',
    logout: '#DC2626',
    white: '#FFFFFF',
    adminPrimary: '#F2F8FF',
    adminAccent: '#64A7D3',
    adminSurface: '#FFFFFF',
    adminText: '#2A3440',
  },
  radius: {
    sm: 14,
    md: 16,
    lg: 22,
    pill: 999,
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 28,
  },
  shadows: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 6,
    },
    button: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.16,
      shadowRadius: 10,
      elevation: 6,
    },
  },
};

export const notificationPalette = {
  success: { bg: '#E6F7F0', text: '#2F7C5D', icon: 'checkmark-circle' },
  error: { bg: '#FEE2E2', text: '#991B1B', icon: 'alert-circle' },
  warning: { bg: '#FEF3C7', text: '#8A6726', icon: 'warning' },
  info: { bg: '#EAF3FF', text: '#3A6C9F', icon: 'information-circle' },
};
